### ISSUE TITLE
Insufficient data for forecast forecast_0

### ISSUE THREAD

**Issue by macjeff** [bpaauwe/udi-owm-poly#6]
Keep getting that and a simple restart of the NS fixes the issue so it seems.  Attached screenshot and logs if you want to take a look.

[OpenWeatherMap_logs_2020-6-11_211350.zip](https://github.com/bpaauwe/udi-owm-poly/files/4768118/OpenWeatherMap_logs_2020-6-11_211350.zip)
<img width="787" alt="Screen Shot 2020-06-11 at 9 13 58 PM" src="https://user-images.githubusercontent.com/20373758/84454535-beeb9180-ac28-11ea-97e2-9bb56c8fd2e5.png">

**Comment by macjeff** [comment]
Update- Restart of node server fixed it the other day but not today.  And ran latest update and right away same issue.

**Comment by bpaauwe** [comment]
It's not something that can be fixed as it's not an error. That's the normal behavior. You are being notified that OpenWeatherMap has not provided enough data to generate a daily forecast.

**Comment by macjeff** [comment]
Also do you see all the DEBUG in my logs.  I have it set Logging OFF in the ISY.  I reported that as a separate issue.

and as far as this I just ignore it?   I tend to want to react to any errors - especially in BLUE   LOL

**Comment by psmith3** [comment]
> Update- Restart of node server fixed it the other day but not today. And ran latest update and right away same issue.

I am seeing this too. I just renamed the Forecast 0 node as "not used".

**Comment by CompKingCanada** [comment]
The core issue is that the weather provider provides forecast data in 3 hour increments.  Day 0 is the forecast of the the current day.  All weather forecasts summarize the 3 hours increments into a daily forecast by averaging values (other than max/min values which record the absolute limit).  As the day progresses, the amount of forecast data available becomes limited as part of the day has moved from "forecast" to "actual"

The code currently ignores all days which aren't "complete days" (i.e. they don't have 8 separate 3 hour segments of remaining forecast)

Option:  For Day 0 forecast, allow the remaining hours of available forecast to be used in populating Forecast 0.  This would result in Forecast 0 values changing every 3 hours as segments drop off.

Issue:
This node would act differently than other Poly weather interfaces..  But this is a difference due to the way forecasting is done by the provider.  

I like this idea, as it uses the remaining forecasted data that's available, which is likely more granular than other weather services, and provides value by updating Node 0 for a "remainder of current day" metric.

**Comment by bpaauwe** [comment]
No, not only would it act differently, it would be inacurate. Reporting a temperature min/max for a 6 hour window of the day is likely very different than the min/max for all 24 hours.

The solution for OWM is to switch the node server to use the new daily forecast data API that OWM recently released.  Once I have the time, I'll update the node server.
